"""Scheme pack loader / validator / SQL renderer.

A scheme pack (schemes/<CODE>.toml) is the single source of truth for one legal scheme:

  [scheme]        code, state_code, constitution, name, primary_law, rules_version,
                  model_bye_laws_version, effective_from, status, source_reference
  [[parameter]]   one entry per rule the engine reads: its instrument and provision, whether it is
                  statutory, its baseline value, who may vary it (layers), within what limits, how it
                  is enforced, which code reads it (`feeds`) and how far its text has been checked.

Everything derived from a pack - the SQL seed block in database/estatehub.sql, the Master rule editor's
RULE_SPECS, the society-level resolver's definitions - is generated from it, so a rule is written once.
Python >= 3.11 (tomllib).
"""
from __future__ import annotations

import re
import tomllib
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

PACK_DIR = Path(__file__).resolve().parent

NATURES = ("statutory", "non_statutory")
BASE_SOURCES = ("central", "state_act_rules", "model_bye_law", "engine_default")
STATUTORY_SOURCES = ("central", "state_act_rules")
TYPES = ("int", "num", "text")
ENFORCEMENTS = ("hard_wired", "gated", "tracked", "policy")
VERIFICATIONS = ("provisional", "checked", "verified", "disputed")
TIGHTEN = ("lower", "higher", "none")
CONSTITUTIONS = ("AOA", "REG_SOCIETY", "COOP", "GENERIC")
STATUSES = ("active", "retired", "draft")
_KEY_RE = re.compile(r"^[a-z][a-z0-9_]{1,29}$")      # <= 30: the key doubles as resolutions.clause_id (VARCHAR(30))

BEGIN_MARK = "-- >>> GENERATED by scripts/build_scheme_sql.py from schemes/*.toml. Do not edit by hand."
END_MARK = "-- <<< END GENERATED"


class PackError(ValueError):
    """A scheme pack is malformed. The message lists every problem found."""


@dataclass(frozen=True)
class Param:
    key: str
    label: str
    instrument: str
    provision: str
    clause: str | None
    nature: str
    base_source: str
    type: str
    unit: str | None
    value: float | int | None
    value_text: str | None
    min: float | None
    max: float | None
    vary_min: float | None
    vary_max: float | None
    choices: tuple[str, ...]
    layers: tuple[int, ...]
    tighten: str
    droppable: bool
    enforcement: str
    feeds: tuple[str, ...]
    verification: str
    verified_on: date | None
    needs_decision: bool
    implemented: bool
    source: str
    description: str

    @property
    def statutory(self) -> bool:
        return self.nature == "statutory"

    @property
    def base_layer(self) -> int | None:
        """0 = Act / Rules / Central Act, 1 = Model Bye-Law, None = engine default (no authority behind it)."""
        return {"central": 0, "state_act_rules": 0, "model_bye_law": 1}.get(self.base_source)


@dataclass(frozen=True)
class Scheme:
    code: str
    state_code: str
    constitution: str
    name: str
    primary_law: str
    rules_version: str | None
    model_bye_laws_version: str | None
    effective_from: date
    status: str
    source_reference: str
    params: tuple[Param, ...] = field(default_factory=tuple)
    path: str = ""

    def param(self, key: str) -> Param | None:
        return next((p for p in self.params if p.key == key), None)


def _num(v):
    return None if v is None else (int(v) if isinstance(v, int) and not isinstance(v, bool) else float(v))


def _parse_param(raw: dict, where: str, errors: list[str]) -> Param | None:
    def err(msg):
        errors.append(f"{where}: {msg}")

    key = raw.get("key", "")
    where = f"{where} [{key or '?'}]"
    n0 = len(errors)
    if not _KEY_RE.match(str(key)):
        err("key must be lower_snake_case, 2-30 characters")
    implemented = bool(raw.get("implemented", True))
    for req in ("label", "instrument", "provision", "nature", "base_source", "type", "enforcement", "source"):
        if raw.get(req) in (None, "", []):
            err(f"'{req}' is required")
    if implemented and not raw.get("feeds"):
        err("'feeds' (the code that reads this parameter) is required unless implemented = false")
    nature, src, typ = raw.get("nature"), raw.get("base_source"), raw.get("type")
    if nature not in NATURES:
        err(f"nature must be one of {NATURES}")
    if src not in BASE_SOURCES:
        err(f"base_source must be one of {BASE_SOURCES}")
    if typ not in TYPES:
        err(f"type must be one of {TYPES}")
    if nature in NATURES and src in BASE_SOURCES and (nature == "statutory") != (src in STATUTORY_SOURCES):
        err("nature is 'statutory' exactly when base_source is 'central' or 'state_act_rules'")
    enf = raw.get("enforcement")
    if enf not in ENFORCEMENTS:
        err(f"enforcement must be one of {ENFORCEMENTS}")
    elif (enf == "policy") != (src == "engine_default"):
        err("enforcement 'policy' is for engine_default parameters only (and they use nothing else)")
    ver = raw.get("verification", "provisional")
    if ver not in VERIFICATIONS:
        err(f"verification must be one of {VERIFICATIONS}")
    vdate = raw.get("verified_on")
    if ver in ("checked", "verified") and not isinstance(vdate, date):
        err("verified_on (a date) is required when verification is 'checked' or 'verified'")
    tighten = raw.get("tighten", "none")
    if tighten not in TIGHTEN:
        err(f"tighten must be one of {TIGHTEN}")
    layers = tuple(raw.get("layers", ()))
    if any(l not in (1, 2, 3) for l in layers):
        err("layers may only contain 1, 2, 3")
    droppable = bool(raw.get("droppable", False))
    if nature == "statutory" and (layers or droppable):
        err("a statutory parameter is Layer 0: layers must be empty and droppable false")
    if droppable and src != "model_bye_law":
        err("only a Model Bye-Law parameter can be droppable (recorded 'not adopted')")
    feeds = raw.get("feeds") or []
    if not isinstance(feeds, list) or not all(isinstance(f, str) and f for f in feeds):
        err("feeds must be a list of function / module names")
    if len(str(raw.get("source", ""))) < 10:
        err("source must cite where the value comes from (at least 10 characters)")
    choices = tuple(raw.get("choices", ()))
    value, vtext = raw.get("value"), raw.get("value_text")
    lo, hi = _num(raw.get("min")), _num(raw.get("max"))
    vlo, vhi = _num(raw.get("vary_min", raw.get("min"))), _num(raw.get("vary_max", raw.get("max")))
    if typ in ("int", "num"):
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            err("a numeric parameter needs a numeric 'value'")
        elif typ == "int" and float(value) != int(value):
            err("an int parameter needs a whole-number value")
        elif (lo is not None and value < lo) or (hi is not None and value > hi):
            err(f"value {value} is outside min/max ({lo}..{hi})")
        if vtext is not None or choices:
            err("a numeric parameter cannot have value_text or choices")
        if lo is None or hi is None:
            err("a numeric parameter needs min and max (sanity bounds)")
        elif vlo is not None and vhi is not None and not (lo <= vlo <= vhi <= hi):
            err("vary_min/vary_max must lie within min/max")
    elif typ == "text":
        if not choices:
            err("a text parameter needs 'choices', ordered loosest to strictest")
        if value is not None:
            err("a text parameter uses value_text, not value")
        if vtext not in choices:
            err("value_text must be one of choices")
    if raw.get("unit") is not None and len(str(raw["unit"])) > 20:
        err("unit is at most 20 characters")
    if len(errors) > n0:
        return None
    return Param(
        key=key, label=str(raw["label"]), instrument=str(raw["instrument"]), provision=str(raw["provision"]),
        clause=raw.get("clause"), nature=nature, base_source=src, type=typ, unit=raw.get("unit"),
        value=_num(value) if typ in ("int", "num") else None, value_text=vtext if typ == "text" else None,
        min=lo, max=hi, vary_min=vlo, vary_max=vhi, choices=choices, layers=layers, tighten=tighten,
        droppable=droppable, enforcement=enf, feeds=tuple(feeds), verification=ver,
        verified_on=vdate if isinstance(vdate, date) else None,
        needs_decision=bool(raw.get("needs_decision", False)), implemented=implemented, source=str(raw["source"]).strip(),
        description=str(raw.get("description", "")).strip())


def parse_pack(text: str, path: str = "<string>") -> Scheme:
    try:
        raw = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise PackError(f"{path}: not valid TOML: {exc}") from exc
    errors: list[str] = []
    s = raw.get("scheme") or {}
    for req in ("code", "state_code", "constitution", "name", "primary_law", "effective_from", "status", "source_reference"):
        if s.get(req) in (None, ""):
            errors.append(f"{path}: [scheme] '{req}' is required")
    if s.get("constitution") not in CONSTITUTIONS:
        errors.append(f"{path}: [scheme] constitution must be one of {CONSTITUTIONS}")
    if s.get("status") not in STATUSES:
        errors.append(f"{path}: [scheme] status must be one of {STATUSES}")
    if s.get("effective_from") is not None and not isinstance(s["effective_from"], date):
        errors.append(f"{path}: [scheme] effective_from must be a date (YYYY-MM-DD)")
    params, seen = [], set()
    for i, rp in enumerate(raw.get("parameter") or []):
        p = _parse_param(rp, f"{path} parameter #{i + 1}", errors)
        if p:
            if p.key in seen:
                errors.append(f"{path}: duplicate parameter key '{p.key}'")
            seen.add(p.key)
            params.append(p)
    if errors:
        raise PackError("\n".join(errors))
    return Scheme(code=s["code"], state_code=s["state_code"], constitution=s["constitution"], name=s["name"],
                  primary_law=s["primary_law"], rules_version=s.get("rules_version"),
                  model_bye_laws_version=s.get("model_bye_laws_version"), effective_from=s["effective_from"],
                  status=s["status"], source_reference=s["source_reference"], params=tuple(params), path=path)


def load_scheme(code: str) -> Scheme:
    path = PACK_DIR / f"{code}.toml"
    return parse_pack(path.read_text(encoding="utf-8"), str(path.name))


def load_all() -> list[Scheme]:
    out = [parse_pack(p.read_text(encoding="utf-8"), p.name) for p in sorted(PACK_DIR.glob("*.toml"))]
    codes = [s.code for s in out]
    if len(codes) != len(set(codes)):
        raise PackError("two packs declare the same scheme code")
    return out


# ── SQL rendering ─────────────────────────────────────────────────────────────
def _q(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return repr(v) if isinstance(v, float) else str(v)
    if isinstance(v, date):
        return f"DATE '{v.isoformat()}'"
    return "'" + str(v).replace("'", "''") + "'"


def _arr(items, kind: str) -> str:
    if not items:
        return f"ARRAY[]::{kind}[]"
    return "ARRAY[" + ", ".join(_q(i) for i in items) + f"]::{kind}[]"


def render_sql(schemes: list[Scheme]) -> str:
    """The generated block for database/estatehub.sql (between BEGIN_MARK and END_MARK, inclusive)."""
    lines = [BEGIN_MARK]
    defs, vals = [], []
    for s in schemes:
        for p in s.params:
            defs.append("(" + ", ".join([
                _q(s.code), _q(p.key), _q(p.label), _q(p.instrument), _q(p.provision), _q(p.clause), _q(p.nature),
                _q(p.base_source), _q(p.type), _q(p.unit), _q(p.min), _q(p.max), _q(p.vary_min), _q(p.vary_max),
                _arr(p.choices, "TEXT"), _arr(p.layers, "INT"), _q(p.tighten), _q(p.droppable), _q(p.enforcement),
                _arr(p.feeds, "TEXT"), _q(p.verification), _q(p.verified_on), _q(p.needs_decision),
                _q(p.implemented), _q(p.description or None)]) + ")")
            vals.append("(" + ", ".join([_q(s.code), _q(p.key), _q(p.value), _q(p.value_text), _q(p.unit),
                                         _q(p.source), _q(s.effective_from)]) + ")")
    lines.append("INSERT INTO rule_parameter_defs (regime_code, rule_key, label, instrument, provision, clause_id, nature,\n"
                 "    base_source, value_type, unit, min_value, max_value, vary_min, vary_max, choices, layers, tighten,\n"
                 "    droppable, enforcement, feeds, verification, verified_on, needs_decision, implemented, description) VALUES\n "
                 + ",\n ".join(defs) + "\nON CONFLICT DO NOTHING;")
    lines.append("")
    lines.append("INSERT INTO regime_rule_parameters (regime_code, rule_key, value, value_text, unit, source_reference, effective_from) VALUES\n "
                 + ",\n ".join(vals) + "\nON CONFLICT DO NOTHING;")
    lines.append(END_MARK)
    return "\n".join(lines)
